apiVersion: v1
kind: Service
metadata:
  labels:
    operator: resource-locker-operator
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: resource-locker-operator-certs
  name: controller-manager-metrics
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    operator: resource-locker-operator
